arch:
- amd64
os: linux
dist: bionic
language: shell
jobs:
  include:
  - script:
    - make image
  - arch: arm64
    script:
    - make image
    env:
    - BUILDARCH=armv71
deploy:
- provider: script
  script: bash deploy.sh $DOCKER_USERNAME $DOCKER_PASSWORD
  on:
    branch: master
env:
  global:
  - DEFAULTIMAGE=jchorl/go-build:latest
  - DOCKER_USERNAME=jchorl
  - secure: ujb7r8g08CFIjWo9ILzEiTXMowoW+txZbO+fWsQqZxTmRdBBWHdiRbcJ95gDEKHLWMbIHpPqIt1qqBMpNaoHH4eX6axYVYcs77v27oRg5/E/768G08odiEW47e8D05r+YMlL2btuDYrZXZ/g0HXbEoJ6yk0HTwXef+IWLeNcvqZhOPRF8fn6FdIp9ehgkrCUFHwLlYrRmZBI1cCud1BXQUJ9NIvhC3BlU0RMSIFFgBqNdwHyctZWmjR1+LJPJ3O1BG8IDLtAbmBpB3t3SnMzXSNgIIfKzFZBoJkZFl48O/aqveCUoRVwhaxTOJtDS6IlwrIw7ZJfZcfshNrCl24d8Rm3DioDec7vbR4P1Gfzl3VR0gpYaX151T3rPLtKCNaDlodAp3Yqhz8O55kFRlD6gzwPoU6anvI9cEmmebKZHdclU6KVBMJI9Y4PX4loUSn6zRgVmu0oxbyBjEQ/asugYoZD4Crxmuewev5GwcEfJ7VdFoeiUy8phlUzRY3ovEH4Xi0wPcstp3BAnW/uJevOCmxrGxRCWCrGq/eFs2J/h3eqUZbFL11pN584FgX84H/7KDt/eIYamq73mHhPT2nKWmb51xB3dXmur3C89iV2PR+6jPFnrQxlD2JhBFYvc8xAYaXOCwQxcQiPQswFXmT8/fHIAR+EvpAJAZMG0+YJBik=
